ALTER TABLE TABLE_ROUNDS
ADD COLUMN id_jogador_perdedor UUID;

ALTER TABLE TABLE_ROUNDS ADD FOREIGN KEY (id_jogador_perdedor) REFERENCES TABLE_PLAYERS(id);

ALTER TABLE TABLE_MATCHES
ADD COLUMN player_loser UUID;

ALTER TABLE TABLE_MATCHES ADD FOREIGN KEY (player_loser) REFERENCES TABLE_PLAYERS(id);

