CREATE TABLE TABLE_MATCHES (
    id UUID PRIMARY KEY,
    player1 UUID NOT NULL,
    player2 UUID NOT NULL,
    player_winner UUID,
    status VARCHAR(20) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (player1) REFERENCES TABLE_PLAYERS(id),
    FOREIGN KEY (player2) REFERENCES TABLE_PLAYERS(id)
);
