CREATE TABLE TABLE_PLAYER_HANDS (
    id_mao_jogador UUID PRIMARY KEY,
    id_rodada UUID NOT NULL,
    id_jogador UUID NOT NULL,
    id_carta1 VARCHAR(12) NOT NULL,
    id_carta2 VARCHAR(12) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_rodada) REFERENCES TABLE_ROUNDS(id),
    FOREIGN KEY (id_jogador) REFERENCES TABLE_PLAYERS(id),
    FOREIGN KEY (id_carta1) REFERENCES TABLE_CARDS(id),
    FOREIGN KEY (id_carta2) REFERENCES TABLE_CARDS(id)
);