CREATE TABLE TABLE_COMMUNITY_CARDS (
    id UUID PRIMARY KEY,
    id_rodada UUID NOT NULL,
    id_carta VARCHAR(12) NOT NULL,
    visivel BOOLEAN NOT NULL,
    FOREIGN KEY (id_rodada) REFERENCES TABLE_ROUNDS(id),
    FOREIGN KEY (id_carta) REFERENCES TABLE_CARDS(id)
);