CREATE TABLE TABLE_BETS (
    id UUID PRIMARY KEY,
    id_rodada UUID NOT NULL,
    id_jogador UUID NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_rodada) REFERENCES TABLE_ROUNDS(id),
    FOREIGN KEY (id_jogador) REFERENCES TABLE_PLAYERS(id)
);